import React from "react";

import Head from "next/head";
import { Basic as Layout } from "../components/Layout/Basic";
import { HeroSection } from "../components/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <HeroSection />
      </Layout>
    </>
  );
}
